site_name: Hartman.Coffee
site_url: https://hartman.coffee/
copyright: "© 2024 Jesse Hartman. All rights reserved."

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate  
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Music: music.md
  - The Coffee Podcast: podcast.md
  - Apps:
    - Quotr:
      - Overview: apps/quotr/index.md
      - Privacy Policy: apps/quotr/privacy-policy.md

markdown_extensions:
  - attr_list
  - md_in_html
